# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CREATE UNSW
email: create@createunsw.com.au
description: "CreateUNSW runs and provides workshops for beginners on electronics, programming, soldering, prototyping and 3D modelling. Weekly sales of electronic components on-campus, including Kits. Hackerspaces and makerspaces. Quadcopters. Funding and support for student projects."
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
permalink: /:categories/:title/
future: true
plugins: [jekyll-paginate, kramdown, jekyll-seo-tag, jekyll-sitemap]
markdown: kramdown
include: ['_pages']

collections:
  _products:
    output: true
    permalink: /store/:title/
  _media:
    output: true
    permalink: /:categories/:title/
  _people:
    output: true
    permalink: /team/:title/
  _projects:
    output: true
    permalink: /projects/:title/
